### PR TITLE
pull for tyler

### PR DESCRIPTION
**Pull request by PeterLynnSmith**
@bontgoy 
I tried to make a little change so that I would have something to compare from master to the new branch but it only seems to be showing the tiny little change I made. The actual link is below. In command line I created a feature branch, made a small edit to the file and saved, then added and committed, then pushed from the new branch, then in github created a pull request. Before I tried this without making the small change and it didn't let me create the pull request comparing master to the feature branch or the other way around.

https://github.com/PeterLynnSmith/phase-0-tracks/blob/master/ruby/vampires.rb

### CODE REVIEW

**Comment by Bontgoy** [comment]
@PeterLynnSmith how can I best facilitate a learning experience out of this code review for you.

You have been doing a good job coming to office hours do you have an understanding of looping and conditions at this point?  Could you resubmit this PR with a working allergy loop?

Something I am noticing is that you are using `case` in such a way that is very much not intended.  Doing some research on `case` vs `if/else` may e helpful.

Reach out if you have questions but at this point I would like you to update this exercise based on the things we have been going over in office hours this week and let me know so I can see what you are learning.

**Comment by PeterLynnSmith** [comment]
I did the allergy loop successfully but then started getting lots of errors when trying to do the number of employees loop. I reorganized my conditionals in an effort to condense them so I'm trying to get everything working without the number of employees loop. I'll post when I get it working. See you at 1! (pacific)

**Comment by Bontgoy** [comment]
@PeterLynnSmith read this and work through it as you go

https://pine.fm/LearnToProgram/chap_06.html

reach out if you want to talk about what is going on with flow control and let me know if there are still some dark points.  It is important to pick up on this stuff now and stay diligent.

**Comment by PeterLynnSmith** [comment]
Awesome website, thanks! I'll be sure to let you know how it goes as well as some other resources I'm working through. I wish I could come to office hours tomorrow but I have to work this weekend! Learning about some new types of iteration and loops and a gigantic amount in general from my pairs literally all day also has really cleared this stuff up. We got everything working like a dream but I should redo it all on my own before submitting it to you to make sure I can now do it without help from them. Very exciting to finally see this run properly 👍

**Pull request merged**
